/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContextScanSnapshot {
  'stressLevel' : bigint,
  'mood' : bigint,
  'notes' : string,
  'crowdDensity' : string,
  'socialEnergy' : bigint,
  'weather' : string,
}
export interface EventDrift {
  'lifeAltering' : bigint,
  'averageWeek' : bigint,
  'currentTrajectory' : bigint,
  'unusual' : bigint,
  'highImpact' : bigint,
}
export interface OutcomeSession {
  'id' : bigint,
  'created' : Time,
  'riskTolerance' : string,
  'contextScan' : [] | [ContextScanSnapshot],
  'recommendations' : Array<Recommendation>,
  'user' : Principal,
  'eventDrift' : EventDrift,
  'timeHorizon' : string,
  'outcome' : string,
}
export interface Recommendation {
  'adjustment' : string,
  'explanation' : string,
}
export type SessionId = bigint;
export type Time = bigint;
export interface UserProfile {
  'region' : string,
  'city' : string,
  'preferences' : string,
  'probabilityDebt' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContextScan' : ActorMethod<[SessionId, ContextScanSnapshot], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOutcomeSession' : ActorMethod<[string, string, string], SessionId>,
  'generateRecommendations' : ActorMethod<
    [SessionId, boolean],
    Array<Recommendation>
  >,
  'getAllSessions' : ActorMethod<[], Array<OutcomeSession>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSession' : ActorMethod<[SessionId], OutcomeSession>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSessions' : ActorMethod<[Principal], Array<OutcomeSession>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];