/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Nat;
export const ContextScanSnapshot = IDL.Record({
  'stressLevel' : IDL.Nat,
  'mood' : IDL.Nat,
  'notes' : IDL.Text,
  'crowdDensity' : IDL.Text,
  'socialEnergy' : IDL.Nat,
  'weather' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Recommendation = IDL.Record({
  'adjustment' : IDL.Text,
  'explanation' : IDL.Text,
});
export const Time = IDL.Int;
export const EventDrift = IDL.Record({
  'lifeAltering' : IDL.Nat,
  'averageWeek' : IDL.Nat,
  'currentTrajectory' : IDL.Nat,
  'unusual' : IDL.Nat,
  'highImpact' : IDL.Nat,
});
export const OutcomeSession = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'riskTolerance' : IDL.Text,
  'contextScan' : IDL.Opt(ContextScanSnapshot),
  'recommendations' : IDL.Vec(Recommendation),
  'user' : IDL.Principal,
  'eventDrift' : EventDrift,
  'timeHorizon' : IDL.Text,
  'outcome' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'region' : IDL.Text,
  'city' : IDL.Text,
  'preferences' : IDL.Text,
  'probabilityDebt' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContextScan' : IDL.Func([SessionId, ContextScanSnapshot], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOutcomeSession' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SessionId],
      [],
    ),
  'generateRecommendations' : IDL.Func(
      [SessionId, IDL.Bool],
      [IDL.Vec(Recommendation)],
      [],
    ),
  'getAllSessions' : IDL.Func([], [IDL.Vec(OutcomeSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSession' : IDL.Func([SessionId], [OutcomeSession], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSessions' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(OutcomeSession)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Nat;
  const ContextScanSnapshot = IDL.Record({
    'stressLevel' : IDL.Nat,
    'mood' : IDL.Nat,
    'notes' : IDL.Text,
    'crowdDensity' : IDL.Text,
    'socialEnergy' : IDL.Nat,
    'weather' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Recommendation = IDL.Record({
    'adjustment' : IDL.Text,
    'explanation' : IDL.Text,
  });
  const Time = IDL.Int;
  const EventDrift = IDL.Record({
    'lifeAltering' : IDL.Nat,
    'averageWeek' : IDL.Nat,
    'currentTrajectory' : IDL.Nat,
    'unusual' : IDL.Nat,
    'highImpact' : IDL.Nat,
  });
  const OutcomeSession = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'riskTolerance' : IDL.Text,
    'contextScan' : IDL.Opt(ContextScanSnapshot),
    'recommendations' : IDL.Vec(Recommendation),
    'user' : IDL.Principal,
    'eventDrift' : EventDrift,
    'timeHorizon' : IDL.Text,
    'outcome' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'region' : IDL.Text,
    'city' : IDL.Text,
    'preferences' : IDL.Text,
    'probabilityDebt' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContextScan' : IDL.Func([SessionId, ContextScanSnapshot], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOutcomeSession' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SessionId],
        [],
      ),
    'generateRecommendations' : IDL.Func(
        [SessionId, IDL.Bool],
        [IDL.Vec(Recommendation)],
        [],
      ),
    'getAllSessions' : IDL.Func([], [IDL.Vec(OutcomeSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSession' : IDL.Func([SessionId], [OutcomeSession], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSessions' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(OutcomeSession)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };